services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s

  db_service:
    build:
      context: .
      dockerfile: ./db_service/Dockerfile
    container_name: db_service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/api/mails || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s

  mq:
    image: rabbitmq:3-management
    container_name: mq
    restart: always
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 3s
      retries: 15
      start_period: 5s

  main_service:
    build:
      context: .
      dockerfile: ./main_service/Dockerfile
    container_name: main_service
    depends_on:
      db_service:
        condition: service_healthy
      mq:
        condition: service_healthy
    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/bank/mails || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s

  front:
    build:
      context: ./front
    container_name: front
    depends_on:
      main_service:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_MAIN_API_URL: "http://localhost:8000"
  
  #ai_service:
  #  build:
  #    context: .
  #    dockerfile: ./ai_service/Dockerfile
  #  container_name: ai_service
  #  depends_on:
  #    mq:
  #      condition: service_healthy
  #  environment:
  #    RABBITMQ_URL: amqp://guest:guest@mq:5672/
  #  volumes:
  #    - ./ai_service/logs:/app/logs
  #  restart: unless-stopped

  email_generator:
    build:
      context: ./email_generator
      dockerfile: Dockerfile
    container_name: email_generator
    depends_on:
      mq:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
