services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_service:
    build:
      context: .
      dockerfile: ./db_service/Dockerfile
    container_name: db_service
    depends_on:
      - db
    ports:
      - "8001:8001"

  mq:
    image: rabbitmq:3-management
    container_name: mq
    restart: always
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  main_service:
    build:
      context: .
      dockerfile: ./main_service/Dockerfile
    container_name: main_service
    depends_on:
      - db_service
      - mq
    ports:
      - "8000:8000"

  front:
    build:
      context: ./front
    container_name: front
    depends_on:
      - main_service
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_MAIN_API_URL: "http://localhost:8000"

volumes:
  pgdata:
